export const SUCCESS = 'STATUS_SUCCESS'
export const FAILURE = 'STATUS_FAILURE'
export const LOADING = 'STATUS_LOADING'
export const PERSIST = 'STATUS_PERSIST'
export const IDLE = 'STATUS_IDLE'

export const GET_DASHBOARD_DATA_REQUEST = 'GET_DASHBOARD_DATA_REQUEST'
export const GET_DASHBOARD_DATA_SUCCESS = 'GET_DASHBOARD_DATA_SUCCESS'
export const GET_DASHBOARD_DATA_FAILURE = 'GET_DASHBOARD_DATA_FAILURE'
export const GET_DASHBOARD_DATA_IDLE = 'GET_DASHBOARD_DATA_IDLE'

export const UPDATE_DASHBOARD_DATA_REQUEST = 'UPDATE_DASHBOARD_DATA_REQUEST'
export const UPDATE_DASHBOARD_DATA_SUCCESS = 'UPDATE_DASHBOARD_DATA_SUCCESS'
export const UPDATE_DASHBOARD_DATA_FAILURE = 'UPDATE_DASHBOARD_DATA_FAILURE'

export const SUBMIT_ALL_DASHBOARD_DATA_REQUEST = 'SUBMIT_ALL_DASHBOARD_DATA_REQUEST'
export const SUBMIT_ALL_DASHBOARD_DATA_SUCCESS = 'SUBMIT_ALL_DASHBOARD_DATA_SUCCESS'
export const SUBMIT_ALL_DASHBOARD_DATA_FAILURE = 'SUBMIT_ALL_DASHBOARD_DATA_FAILURE'

export const SUBMIT_ONE_DASHBOARD_DATA_REQUEST = 'SUBMIT_ONE_DASHBOARD_DATA_REQUEST'
export const SUBMIT_ONE_DASHBOARD_DATA_SUCCESS = 'SUBMIT_ONE_DASHBOARD_DATA_SUCCESS'
export const SUBMIT_ONE_DASHBOARD_DATA_FAILURE = 'SUBMIT_ONE_DASHBOARD_DATA_FAILURE'

export const GET_FIELDS_PER_ENTITY_REQUEST = 'GET_FIELDS_PER_ENTITY_REQUEST'
export const GET_FIELDS_PER_ENTITY_SUCCESS = 'GET_FIELDS_PER_ENTITY_SUCCESS'
export const GET_FIELDS_PER_ENTITY_FAILURE = 'GET_FIELDS_PER_ENTITY_FAILURE'
export const GET_FIELDS_PER_ENTITY_IDLE = 'GET_FIELDS_PER_ENTITY_IDLE'

export const UPDATE_FIELDS_DATA_REQUEST = 'UPDATE_FIELDS_DATA_REQUEST'
export const UPDATE_FIELDS_DATA_SUCCESS = 'UPDATE_FIELDS_DATA_SUCCESS'
export const UPDATE_FIELDS_DATA_FAILURE = 'UPDATE_FIELDS_DATA_FAILURE'

export const GET_STASHES_DATA_REQUEST = 'GET_STASHES_DATA_REQUEST'
export const GET_STASHES_DATA_SUCCESS = 'GET_STASHES_DATA_SUCCESS'
export const GET_STASHES_DATA_FAILURE = 'GET_STASHES_DATA_FAILURE'
export const GET_STASHES_DATA_IDLE = 'GET_STASHES_DATA_IDLE'

export const UPDATE_STASHES_DATA_REQUEST = 'UPDATE_STASHES_DATA_REQUEST'
export const UPDATE_STASHES_DATA_SUCCESS = 'UPDATE_STASHES_DATA_SUCCESS'
export const UPDATE_STASHES_DATA_FAILURE = 'UPDATE_STASHES_DATA_FAILURE'

export const SET_STASHES_DATA_REQUEST = 'SET_STASHES_DATA_REQUEST'
export const SET_STASHES_DATA_SUCCESS = 'SET_STASHES_DATA_SUCCESS'
export const SET_STASHES_DATA_FAILURE = 'SET_STASHES_DATA_FAILURE'